// Code generated by protoc-gen-go. DO NOT EDIT.
// source: sawtooth-go-sdk/protobuf/client_status_pb2/client_status.proto

/*
Package client_status is a generated protocol buffer package.

It is generated from these files:
	sawtooth-go-sdk/protobuf/client_status_pb2/client_status.proto

It has these top-level messages:
	ClientStatusGetRequest
	ClientStatusGetResponse
*/
package client_status

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// The status of the response message, not the validator's status
type ClientStatusGetResponse_Status int32

const (
	ClientStatusGetResponse_STATUS_UNSET ClientStatusGetResponse_Status = 0
	ClientStatusGetResponse_OK           ClientStatusGetResponse_Status = 1
	ClientStatusGetResponse_ERROR        ClientStatusGetResponse_Status = 2
)

var ClientStatusGetResponse_Status_name = map[int32]string{
	0: "STATUS_UNSET",
	1: "OK",
	2: "ERROR",
}
var ClientStatusGetResponse_Status_value = map[string]int32{
	"STATUS_UNSET": 0,
	"OK":           1,
	"ERROR":        2,
}

func (x ClientStatusGetResponse_Status) String() string {
	return proto.EnumName(ClientStatusGetResponse_Status_name, int32(x))
}
func (ClientStatusGetResponse_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{1, 0}
}

// A request to get miscellaneous information about the validator
type ClientStatusGetRequest struct {
}

func (m *ClientStatusGetRequest) Reset()                    { *m = ClientStatusGetRequest{} }
func (m *ClientStatusGetRequest) String() string            { return proto.CompactTextString(m) }
func (*ClientStatusGetRequest) ProtoMessage()               {}
func (*ClientStatusGetRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type ClientStatusGetResponse struct {
	Status ClientStatusGetResponse_Status  `protobuf:"varint,1,opt,name=status,enum=ClientStatusGetResponse_Status" json:"status,omitempty"`
	Peers  []*ClientStatusGetResponse_Peer `protobuf:"bytes,2,rep,name=peers" json:"peers,omitempty"`
	// The validator's public network endpoint
	Endpoint string `protobuf:"bytes,3,opt,name=endpoint" json:"endpoint,omitempty"`
}

func (m *ClientStatusGetResponse) Reset()                    { *m = ClientStatusGetResponse{} }
func (m *ClientStatusGetResponse) String() string            { return proto.CompactTextString(m) }
func (*ClientStatusGetResponse) ProtoMessage()               {}
func (*ClientStatusGetResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ClientStatusGetResponse) GetStatus() ClientStatusGetResponse_Status {
	if m != nil {
		return m.Status
	}
	return ClientStatusGetResponse_STATUS_UNSET
}

func (m *ClientStatusGetResponse) GetPeers() []*ClientStatusGetResponse_Peer {
	if m != nil {
		return m.Peers
	}
	return nil
}

func (m *ClientStatusGetResponse) GetEndpoint() string {
	if m != nil {
		return m.Endpoint
	}
	return ""
}

// Information about the validator's peers
type ClientStatusGetResponse_Peer struct {
	// The peer's public network endpoint
	Endpoint string `protobuf:"bytes,1,opt,name=endpoint" json:"endpoint,omitempty"`
}

func (m *ClientStatusGetResponse_Peer) Reset()                    { *m = ClientStatusGetResponse_Peer{} }
func (m *ClientStatusGetResponse_Peer) String() string            { return proto.CompactTextString(m) }
func (*ClientStatusGetResponse_Peer) ProtoMessage()               {}
func (*ClientStatusGetResponse_Peer) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 0} }

func (m *ClientStatusGetResponse_Peer) GetEndpoint() string {
	if m != nil {
		return m.Endpoint
	}
	return ""
}

func init() {
	proto.RegisterType((*ClientStatusGetRequest)(nil), "ClientStatusGetRequest")
	proto.RegisterType((*ClientStatusGetResponse)(nil), "ClientStatusGetResponse")
	proto.RegisterType((*ClientStatusGetResponse_Peer)(nil), "ClientStatusGetResponse.Peer")
	proto.RegisterEnum("ClientStatusGetResponse_Status", ClientStatusGetResponse_Status_name, ClientStatusGetResponse_Status_value)
}

func init() {
	proto.RegisterFile("sawtooth-go-sdk/protobuf/client_status_pb2/client_status.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 250 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xb2, 0x2e, 0x4e, 0x2c, 0x2f,
	0xc9, 0xcf, 0x2f, 0xc9, 0x88, 0x2f, 0x4e, 0xc9, 0xd6, 0x2f, 0x28, 0xca, 0x2f, 0xc9, 0x4f, 0x2a,
	0x4d, 0xd3, 0x4f, 0xce, 0xc9, 0x4c, 0xcd, 0x2b, 0x89, 0x2f, 0x2e, 0x49, 0x2c, 0x29, 0x2d, 0x8e,
	0x2f, 0x48, 0x32, 0x42, 0x15, 0xd1, 0x03, 0x2b, 0x54, 0x92, 0xe0, 0x12, 0x73, 0x06, 0x0b, 0x07,
	0x83, 0x45, 0xdd, 0x53, 0x4b, 0x82, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x94, 0xbe, 0x31, 0x72,
	0x89, 0x63, 0x48, 0x15, 0x17, 0xe4, 0xe7, 0x15, 0xa7, 0x0a, 0x99, 0x73, 0xb1, 0x41, 0x4c, 0x91,
	0x60, 0x54, 0x60, 0xd4, 0xe0, 0x33, 0x92, 0xd7, 0xc3, 0xa1, 0x52, 0x0f, 0x22, 0x12, 0x04, 0x55,
	0x2e, 0x64, 0xcc, 0xc5, 0x5a, 0x90, 0x9a, 0x5a, 0x54, 0x2c, 0xc1, 0xa4, 0xc0, 0xac, 0xc1, 0x6d,
	0x24, 0x8b, 0x53, 0x5f, 0x00, 0x50, 0x55, 0x10, 0x44, 0xad, 0x90, 0x14, 0x17, 0x47, 0x6a, 0x5e,
	0x4a, 0x41, 0x7e, 0x66, 0x5e, 0x89, 0x04, 0x33, 0xd0, 0x3e, 0xce, 0x20, 0x38, 0x5f, 0x4a, 0x89,
	0x8b, 0x05, 0xa4, 0x14, 0x45, 0x0d, 0x23, 0xaa, 0x1a, 0x25, 0x5d, 0x2e, 0x36, 0x88, 0x05, 0x42,
	0x02, 0x5c, 0x3c, 0xc1, 0x21, 0x8e, 0x21, 0xa1, 0xc1, 0xf1, 0xa1, 0x7e, 0xc1, 0xae, 0x21, 0x02,
	0x0c, 0x42, 0x6c, 0x5c, 0x4c, 0xfe, 0xde, 0x02, 0x8c, 0x42, 0x9c, 0x5c, 0xac, 0xae, 0x41, 0x41,
	0xfe, 0x41, 0x02, 0x4c, 0x4e, 0x1a, 0x5c, 0xa2, 0xb0, 0x10, 0xd5, 0x03, 0x86, 0xa8, 0x1e, 0x2c,
	0x44, 0x03, 0x18, 0xa3, 0x78, 0x51, 0x82, 0x30, 0x89, 0x0d, 0x2c, 0x65, 0x0c, 0x08, 0x00, 0x00,
	0xff, 0xff, 0x22, 0x79, 0xa9, 0x15, 0x82, 0x01, 0x00, 0x00,
}
