// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/rberg2/sawtooth-go-sdk/protobuf/client_receipt_pb2/client_receipt.proto

/*
Package client_receipt_pb2 is a generated protocol buffer package.

It is generated from these files:
	github.com/rberg2/sawtooth-go-sdk/protobuf/client_receipt_pb2/client_receipt.proto

It has these top-level messages:
	ClientReceiptGetRequest
	ClientReceiptGetResponse
*/
package client_receipt_pb2

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import transaction_receipt "github.com/rberg2/sawtooth-go-sdk/protobuf/transaction_receipt_pb2"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ClientReceiptGetResponse_Status int32

const (
	ClientReceiptGetResponse_STATUS_UNSET   ClientReceiptGetResponse_Status = 0
	ClientReceiptGetResponse_OK             ClientReceiptGetResponse_Status = 1
	ClientReceiptGetResponse_INTERNAL_ERROR ClientReceiptGetResponse_Status = 2
	ClientReceiptGetResponse_NO_RESOURCE    ClientReceiptGetResponse_Status = 5
	ClientReceiptGetResponse_INVALID_ID     ClientReceiptGetResponse_Status = 8
)

var ClientReceiptGetResponse_Status_name = map[int32]string{
	0: "STATUS_UNSET",
	1: "OK",
	2: "INTERNAL_ERROR",
	5: "NO_RESOURCE",
	8: "INVALID_ID",
}
var ClientReceiptGetResponse_Status_value = map[string]int32{
	"STATUS_UNSET":   0,
	"OK":             1,
	"INTERNAL_ERROR": 2,
	"NO_RESOURCE":    5,
	"INVALID_ID":     8,
}

func (x ClientReceiptGetResponse_Status) String() string {
	return proto.EnumName(ClientReceiptGetResponse_Status_name, int32(x))
}
func (ClientReceiptGetResponse_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{1, 0}
}

// Fetches a specific txn by its id (header_signature) from the blockchain.
type ClientReceiptGetRequest struct {
	TransactionIds []string `protobuf:"bytes,1,rep,name=transaction_ids,json=transactionIds" json:"transaction_ids,omitempty"`
}

func (m *ClientReceiptGetRequest) Reset()                    { *m = ClientReceiptGetRequest{} }
func (m *ClientReceiptGetRequest) String() string            { return proto.CompactTextString(m) }
func (*ClientReceiptGetRequest) ProtoMessage()               {}
func (*ClientReceiptGetRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ClientReceiptGetRequest) GetTransactionIds() []string {
	if m != nil {
		return m.TransactionIds
	}
	return nil
}

// A response that returns the txn receipt specified by a
// ClientTransactionReceiptGetRequest.
//
// Statuses:
//   * OK - everything worked as expected, txn receipt has been fetched
//   * INTERNAL_ERROR - general error, such as protobuf failing to deserialize
//   * NO_RESOURCE - no receipt exists for the transaction id specified
type ClientReceiptGetResponse struct {
	Status   ClientReceiptGetResponse_Status           `protobuf:"varint,1,opt,name=status,enum=ClientReceiptGetResponse_Status" json:"status,omitempty"`
	Receipts []*transaction_receipt.TransactionReceipt `protobuf:"bytes,2,rep,name=receipts" json:"receipts,omitempty"`
}

func (m *ClientReceiptGetResponse) Reset()                    { *m = ClientReceiptGetResponse{} }
func (m *ClientReceiptGetResponse) String() string            { return proto.CompactTextString(m) }
func (*ClientReceiptGetResponse) ProtoMessage()               {}
func (*ClientReceiptGetResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ClientReceiptGetResponse) GetStatus() ClientReceiptGetResponse_Status {
	if m != nil {
		return m.Status
	}
	return ClientReceiptGetResponse_STATUS_UNSET
}

func (m *ClientReceiptGetResponse) GetReceipts() []*transaction_receipt.TransactionReceipt {
	if m != nil {
		return m.Receipts
	}
	return nil
}

func init() {
	proto.RegisterType((*ClientReceiptGetRequest)(nil), "ClientReceiptGetRequest")
	proto.RegisterType((*ClientReceiptGetResponse)(nil), "ClientReceiptGetResponse")
	proto.RegisterEnum("ClientReceiptGetResponse_Status", ClientReceiptGetResponse_Status_name, ClientReceiptGetResponse_Status_value)
}

func init() {
	proto.RegisterFile("github.com/rberg2/sawtooth-go-sdk/protobuf/client_receipt_pb2/client_receipt.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 301 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x74, 0x91, 0x4f, 0x4b, 0xfb, 0x30,
	0x1c, 0xc6, 0x7f, 0xdd, 0x0f, 0xcb, 0xfc, 0x4e, 0xba, 0x10, 0x11, 0x87, 0xa7, 0xb1, 0x8b, 0xbb,
	0x98, 0x41, 0xbd, 0x78, 0xf1, 0xd0, 0x6d, 0x65, 0x14, 0x47, 0x2b, 0x69, 0xab, 0xe0, 0x25, 0xf4,
	0x4f, 0xc4, 0xa2, 0x34, 0xb5, 0x49, 0xf1, 0xdd, 0xfa, 0x5a, 0xac, 0x6d, 0xa7, 0xd3, 0xcd, 0x5b,
	0x78, 0xf2, 0x3c, 0x9f, 0x27, 0x3c, 0x81, 0x6b, 0x19, 0xbd, 0x29, 0x21, 0xd4, 0x13, 0x93, 0xe9,
	0xf3, 0xac, 0x28, 0x85, 0x12, 0x71, 0xf5, 0x38, 0x4b, 0x5e, 0x32, 0x9e, 0x2b, 0x56, 0xf2, 0x84,
	0x67, 0x85, 0x62, 0x45, 0x6c, 0xfe, 0x92, 0x48, 0x63, 0x3d, 0x5b, 0xed, 0x8f, 0xab, 0x32, 0xca,
	0x65, 0x94, 0xa8, 0x4c, 0xe4, 0x3f, 0x18, 0x7b, 0xf4, 0x16, 0x34, 0x99, 0xc3, 0xe9, 0xa2, 0x29,
	0xa0, 0xad, 0xbc, 0xe2, 0xf5, 0xe9, 0xb5, 0xe2, 0x52, 0xe1, 0x73, 0x18, 0x6e, 0xe7, 0xb2, 0x54,
	0x8e, 0xb4, 0xf1, 0xff, 0xe9, 0x21, 0x35, 0xb6, 0x64, 0x27, 0x95, 0x93, 0x77, 0x0d, 0x46, 0xbb,
	0x10, 0x59, 0x88, 0x5c, 0x72, 0x7c, 0x05, 0xba, 0x54, 0x91, 0xaa, 0x3e, 0xc3, 0xda, 0xd4, 0x30,
	0xc7, 0xe4, 0x2f, 0x2b, 0xf1, 0x1b, 0x1f, 0xed, 0xfc, 0x78, 0x06, 0xfd, 0xee, 0xad, 0x72, 0xd4,
	0xab, 0x8b, 0x07, 0xe6, 0x31, 0x09, 0xbe, 0x9b, 0x3b, 0x00, 0xfd, 0x32, 0x4d, 0xee, 0x41, 0x6f,
	0x11, 0x18, 0xc1, 0x91, 0x1f, 0x58, 0x41, 0xe8, 0xb3, 0xd0, 0xf5, 0xed, 0x00, 0xfd, 0xc3, 0x3a,
	0xf4, 0xbc, 0x1b, 0xa4, 0x61, 0x0c, 0x86, 0xe3, 0x06, 0x36, 0x75, 0xad, 0x35, 0xb3, 0x29, 0xf5,
	0x28, 0xea, 0xe1, 0x21, 0x0c, 0x5c, 0x8f, 0x51, 0xdb, 0xf7, 0x42, 0xba, 0xb0, 0xd1, 0x01, 0x36,
	0x00, 0x1c, 0xf7, 0xce, 0x5a, 0x3b, 0x4b, 0xe6, 0x2c, 0x51, 0x7f, 0x7e, 0x01, 0x27, 0x9b, 0xbd,
	0x49, 0xbd, 0x37, 0xd9, 0xec, 0x7d, 0xab, 0x3d, 0xe0, 0xdd, 0x1f, 0x8b, 0xf5, 0xe6, 0xfe, 0xf2,
	0x23, 0x00, 0x00, 0xff, 0xff, 0xb9, 0x32, 0xcf, 0xe8, 0xe4, 0x01, 0x00, 0x00,
}
