// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/rberg2/sawtooth-go-sdk/protobuf/validator_pb2/validator.proto

/*
Package validator_pb2 is a generated protocol buffer package.

It is generated from these files:
	github.com/rberg2/sawtooth-go-sdk/protobuf/validator_pb2/validator.proto

It has these top-level messages:
	MessageList
	Message
*/
package validator_pb2

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Message_MessageType int32

const (
	Message_DEFAULT Message_MessageType = 0
	// Registration request from the transaction processor to the validator
	Message_TP_REGISTER_REQUEST Message_MessageType = 1
	// Registration response from the validator to the
	// transaction processor
	Message_TP_REGISTER_RESPONSE Message_MessageType = 2
	// Tell the validator that the transaction processor
	// won't take any more transactions
	Message_TP_UNREGISTER_REQUEST Message_MessageType = 3
	// Response from the validator to the tp that it won't
	// send any more transactions
	Message_TP_UNREGISTER_RESPONSE Message_MessageType = 4
	// Process Request from the validator/executor to the
	// transaction processor
	Message_TP_PROCESS_REQUEST Message_MessageType = 5
	// Process response from the transaction processor to the validator/executor
	Message_TP_PROCESS_RESPONSE Message_MessageType = 6
	// State get request from the transaction processor to validator/context_manager
	Message_TP_STATE_GET_REQUEST Message_MessageType = 7
	// State get response from the validator/context_manager to the transaction processor
	Message_TP_STATE_GET_RESPONSE Message_MessageType = 8
	// State set request from the transaction processor to the validator/context_manager
	Message_TP_STATE_SET_REQUEST Message_MessageType = 9
	// State set response from the validator/context_manager to the transaction processor
	Message_TP_STATE_SET_RESPONSE Message_MessageType = 10
	// State delete request from the transaction processor to the validator/context_manager
	Message_TP_STATE_DELETE_REQUEST Message_MessageType = 11
	// State delete response from the validator/context_manager to the transaction processor
	Message_TP_STATE_DELETE_RESPONSE Message_MessageType = 12
	// Message to append data to a transaction receipt
	Message_TP_RECEIPT_ADD_DATA_REQUEST Message_MessageType = 13
	// Response from validator to tell transaction processor that data has been appended
	Message_TP_RECEIPT_ADD_DATA_RESPONSE Message_MessageType = 14
	// Message to add event
	Message_TP_EVENT_ADD_REQUEST Message_MessageType = 15
	// Response from validator to tell transaction processor that event has been created
	Message_TP_EVENT_ADD_RESPONSE Message_MessageType = 16
	// Submission of a batchlist from the web api or another client to the validator
	Message_CLIENT_BATCH_SUBMIT_REQUEST Message_MessageType = 100
	// Response from the validator to the web api/client that the submission was accepted
	Message_CLIENT_BATCH_SUBMIT_RESPONSE Message_MessageType = 101
	// A request to list blocks from the web api/client to the validator
	Message_CLIENT_BLOCK_LIST_REQUEST        Message_MessageType = 102
	Message_CLIENT_BLOCK_LIST_RESPONSE       Message_MessageType = 103
	Message_CLIENT_BLOCK_GET_BY_ID_REQUEST   Message_MessageType = 104
	Message_CLIENT_BLOCK_GET_RESPONSE        Message_MessageType = 105
	Message_CLIENT_BATCH_LIST_REQUEST        Message_MessageType = 106
	Message_CLIENT_BATCH_LIST_RESPONSE       Message_MessageType = 107
	Message_CLIENT_BATCH_GET_REQUEST         Message_MessageType = 108
	Message_CLIENT_BATCH_GET_RESPONSE        Message_MessageType = 109
	Message_CLIENT_TRANSACTION_LIST_REQUEST  Message_MessageType = 110
	Message_CLIENT_TRANSACTION_LIST_RESPONSE Message_MessageType = 111
	Message_CLIENT_TRANSACTION_GET_REQUEST   Message_MessageType = 112
	Message_CLIENT_TRANSACTION_GET_RESPONSE  Message_MessageType = 113
	// Client state request of the current state hash to be retrieved from the journal
	Message_CLIENT_STATE_CURRENT_REQUEST Message_MessageType = 114
	// Response with the current state hash
	Message_CLIENT_STATE_CURRENT_RESPONSE Message_MessageType = 115
	// A request of all the addresses under a particular prefix, for a state hash.
	Message_CLIENT_STATE_LIST_REQUEST Message_MessageType = 116
	// The response of the addresses
	Message_CLIENT_STATE_LIST_RESPONSE Message_MessageType = 117
	// Get the address:data entry at a particular address
	Message_CLIENT_STATE_GET_REQUEST Message_MessageType = 118
	// The response with the entry
	Message_CLIENT_STATE_GET_RESPONSE Message_MessageType = 119
	// A request for the status of a batch or batches
	Message_CLIENT_BATCH_STATUS_REQUEST Message_MessageType = 120
	// A response with the batch statuses
	Message_CLIENT_BATCH_STATUS_RESPONSE Message_MessageType = 121
	// A request for one or more transaction receipts
	Message_CLIENT_RECEIPT_GET_REQUEST Message_MessageType = 122
	// A response with the receipts
	Message_CLIENT_RECEIPT_GET_RESPONSE     Message_MessageType = 123
	Message_CLIENT_BLOCK_GET_BY_NUM_REQUEST Message_MessageType = 124
	// A request for a validator's peers
	Message_CLIENT_PEERS_GET_REQUEST Message_MessageType = 125
	// A response with the validator's peers
	Message_CLIENT_PEERS_GET_RESPONSE                  Message_MessageType = 126
	Message_CLIENT_BLOCK_GET_BY_TRANSACTION_ID_REQUEST Message_MessageType = 127
	Message_CLIENT_BLOCK_GET_BY_BATCH_ID_REQUEST       Message_MessageType = 128
	// A request for a validator's status
	Message_CLIENT_STATUS_GET_REQUEST Message_MessageType = 129
	// A response with the validator's status
	Message_CLIENT_STATUS_GET_RESPONSE Message_MessageType = 130
	// Message types for events
	Message_CLIENT_EVENTS_SUBSCRIBE_REQUEST    Message_MessageType = 500
	Message_CLIENT_EVENTS_SUBSCRIBE_RESPONSE   Message_MessageType = 501
	Message_CLIENT_EVENTS_UNSUBSCRIBE_REQUEST  Message_MessageType = 502
	Message_CLIENT_EVENTS_UNSUBSCRIBE_RESPONSE Message_MessageType = 503
	Message_CLIENT_EVENTS                      Message_MessageType = 504
	Message_CLIENT_EVENTS_GET_REQUEST          Message_MessageType = 505
	Message_CLIENT_EVENTS_GET_RESPONSE         Message_MessageType = 506
	// Temp message types until a discussion can be had about gossip msg
	Message_GOSSIP_MESSAGE                         Message_MessageType = 200
	Message_GOSSIP_REGISTER                        Message_MessageType = 201
	Message_GOSSIP_UNREGISTER                      Message_MessageType = 202
	Message_GOSSIP_BLOCK_REQUEST                   Message_MessageType = 205
	Message_GOSSIP_BLOCK_RESPONSE                  Message_MessageType = 206
	Message_GOSSIP_BATCH_BY_BATCH_ID_REQUEST       Message_MessageType = 207
	Message_GOSSIP_BATCH_BY_TRANSACTION_ID_REQUEST Message_MessageType = 208
	Message_GOSSIP_BATCH_RESPONSE                  Message_MessageType = 209
	Message_GOSSIP_GET_PEERS_REQUEST               Message_MessageType = 210
	Message_GOSSIP_GET_PEERS_RESPONSE              Message_MessageType = 211
	Message_NETWORK_ACK                            Message_MessageType = 300
	Message_NETWORK_CONNECT                        Message_MessageType = 301
	Message_NETWORK_DISCONNECT                     Message_MessageType = 302
	// Message types for Authorization Types
	Message_AUTHORIZATION_CONNECTION_RESPONSE Message_MessageType = 600
	Message_AUTHORIZATION_VIOLATION           Message_MessageType = 601
	Message_AUTHORIZATION_TRUST_REQUEST       Message_MessageType = 602
	Message_AUTHORIZATION_TRUST_RESPONSE      Message_MessageType = 603
	Message_AUTHORIZATION_CHALLENGE_REQUEST   Message_MessageType = 604
	Message_AUTHORIZATION_CHALLENGE_RESPONSE  Message_MessageType = 605
	Message_AUTHORIZATION_CHALLENGE_SUBMIT    Message_MessageType = 606
	Message_AUTHORIZATION_CHALLENGE_RESULT    Message_MessageType = 607
	Message_PING_REQUEST                      Message_MessageType = 700
	Message_PING_RESPONSE                     Message_MessageType = 701
)

var Message_MessageType_name = map[int32]string{
	0:   "DEFAULT",
	1:   "TP_REGISTER_REQUEST",
	2:   "TP_REGISTER_RESPONSE",
	3:   "TP_UNREGISTER_REQUEST",
	4:   "TP_UNREGISTER_RESPONSE",
	5:   "TP_PROCESS_REQUEST",
	6:   "TP_PROCESS_RESPONSE",
	7:   "TP_STATE_GET_REQUEST",
	8:   "TP_STATE_GET_RESPONSE",
	9:   "TP_STATE_SET_REQUEST",
	10:  "TP_STATE_SET_RESPONSE",
	11:  "TP_STATE_DELETE_REQUEST",
	12:  "TP_STATE_DELETE_RESPONSE",
	13:  "TP_RECEIPT_ADD_DATA_REQUEST",
	14:  "TP_RECEIPT_ADD_DATA_RESPONSE",
	15:  "TP_EVENT_ADD_REQUEST",
	16:  "TP_EVENT_ADD_RESPONSE",
	100: "CLIENT_BATCH_SUBMIT_REQUEST",
	101: "CLIENT_BATCH_SUBMIT_RESPONSE",
	102: "CLIENT_BLOCK_LIST_REQUEST",
	103: "CLIENT_BLOCK_LIST_RESPONSE",
	104: "CLIENT_BLOCK_GET_BY_ID_REQUEST",
	105: "CLIENT_BLOCK_GET_RESPONSE",
	106: "CLIENT_BATCH_LIST_REQUEST",
	107: "CLIENT_BATCH_LIST_RESPONSE",
	108: "CLIENT_BATCH_GET_REQUEST",
	109: "CLIENT_BATCH_GET_RESPONSE",
	110: "CLIENT_TRANSACTION_LIST_REQUEST",
	111: "CLIENT_TRANSACTION_LIST_RESPONSE",
	112: "CLIENT_TRANSACTION_GET_REQUEST",
	113: "CLIENT_TRANSACTION_GET_RESPONSE",
	114: "CLIENT_STATE_CURRENT_REQUEST",
	115: "CLIENT_STATE_CURRENT_RESPONSE",
	116: "CLIENT_STATE_LIST_REQUEST",
	117: "CLIENT_STATE_LIST_RESPONSE",
	118: "CLIENT_STATE_GET_REQUEST",
	119: "CLIENT_STATE_GET_RESPONSE",
	120: "CLIENT_BATCH_STATUS_REQUEST",
	121: "CLIENT_BATCH_STATUS_RESPONSE",
	122: "CLIENT_RECEIPT_GET_REQUEST",
	123: "CLIENT_RECEIPT_GET_RESPONSE",
	124: "CLIENT_BLOCK_GET_BY_NUM_REQUEST",
	125: "CLIENT_PEERS_GET_REQUEST",
	126: "CLIENT_PEERS_GET_RESPONSE",
	127: "CLIENT_BLOCK_GET_BY_TRANSACTION_ID_REQUEST",
	128: "CLIENT_BLOCK_GET_BY_BATCH_ID_REQUEST",
	129: "CLIENT_STATUS_GET_REQUEST",
	130: "CLIENT_STATUS_GET_RESPONSE",
	500: "CLIENT_EVENTS_SUBSCRIBE_REQUEST",
	501: "CLIENT_EVENTS_SUBSCRIBE_RESPONSE",
	502: "CLIENT_EVENTS_UNSUBSCRIBE_REQUEST",
	503: "CLIENT_EVENTS_UNSUBSCRIBE_RESPONSE",
	504: "CLIENT_EVENTS",
	505: "CLIENT_EVENTS_GET_REQUEST",
	506: "CLIENT_EVENTS_GET_RESPONSE",
	200: "GOSSIP_MESSAGE",
	201: "GOSSIP_REGISTER",
	202: "GOSSIP_UNREGISTER",
	205: "GOSSIP_BLOCK_REQUEST",
	206: "GOSSIP_BLOCK_RESPONSE",
	207: "GOSSIP_BATCH_BY_BATCH_ID_REQUEST",
	208: "GOSSIP_BATCH_BY_TRANSACTION_ID_REQUEST",
	209: "GOSSIP_BATCH_RESPONSE",
	210: "GOSSIP_GET_PEERS_REQUEST",
	211: "GOSSIP_GET_PEERS_RESPONSE",
	300: "NETWORK_ACK",
	301: "NETWORK_CONNECT",
	302: "NETWORK_DISCONNECT",
	600: "AUTHORIZATION_CONNECTION_RESPONSE",
	601: "AUTHORIZATION_VIOLATION",
	602: "AUTHORIZATION_TRUST_REQUEST",
	603: "AUTHORIZATION_TRUST_RESPONSE",
	604: "AUTHORIZATION_CHALLENGE_REQUEST",
	605: "AUTHORIZATION_CHALLENGE_RESPONSE",
	606: "AUTHORIZATION_CHALLENGE_SUBMIT",
	607: "AUTHORIZATION_CHALLENGE_RESULT",
	700: "PING_REQUEST",
	701: "PING_RESPONSE",
}
var Message_MessageType_value = map[string]int32{
	"DEFAULT":                                    0,
	"TP_REGISTER_REQUEST":                        1,
	"TP_REGISTER_RESPONSE":                       2,
	"TP_UNREGISTER_REQUEST":                      3,
	"TP_UNREGISTER_RESPONSE":                     4,
	"TP_PROCESS_REQUEST":                         5,
	"TP_PROCESS_RESPONSE":                        6,
	"TP_STATE_GET_REQUEST":                       7,
	"TP_STATE_GET_RESPONSE":                      8,
	"TP_STATE_SET_REQUEST":                       9,
	"TP_STATE_SET_RESPONSE":                      10,
	"TP_STATE_DELETE_REQUEST":                    11,
	"TP_STATE_DELETE_RESPONSE":                   12,
	"TP_RECEIPT_ADD_DATA_REQUEST":                13,
	"TP_RECEIPT_ADD_DATA_RESPONSE":               14,
	"TP_EVENT_ADD_REQUEST":                       15,
	"TP_EVENT_ADD_RESPONSE":                      16,
	"CLIENT_BATCH_SUBMIT_REQUEST":                100,
	"CLIENT_BATCH_SUBMIT_RESPONSE":               101,
	"CLIENT_BLOCK_LIST_REQUEST":                  102,
	"CLIENT_BLOCK_LIST_RESPONSE":                 103,
	"CLIENT_BLOCK_GET_BY_ID_REQUEST":             104,
	"CLIENT_BLOCK_GET_RESPONSE":                  105,
	"CLIENT_BATCH_LIST_REQUEST":                  106,
	"CLIENT_BATCH_LIST_RESPONSE":                 107,
	"CLIENT_BATCH_GET_REQUEST":                   108,
	"CLIENT_BATCH_GET_RESPONSE":                  109,
	"CLIENT_TRANSACTION_LIST_REQUEST":            110,
	"CLIENT_TRANSACTION_LIST_RESPONSE":           111,
	"CLIENT_TRANSACTION_GET_REQUEST":             112,
	"CLIENT_TRANSACTION_GET_RESPONSE":            113,
	"CLIENT_STATE_CURRENT_REQUEST":               114,
	"CLIENT_STATE_CURRENT_RESPONSE":              115,
	"CLIENT_STATE_LIST_REQUEST":                  116,
	"CLIENT_STATE_LIST_RESPONSE":                 117,
	"CLIENT_STATE_GET_REQUEST":                   118,
	"CLIENT_STATE_GET_RESPONSE":                  119,
	"CLIENT_BATCH_STATUS_REQUEST":                120,
	"CLIENT_BATCH_STATUS_RESPONSE":               121,
	"CLIENT_RECEIPT_GET_REQUEST":                 122,
	"CLIENT_RECEIPT_GET_RESPONSE":                123,
	"CLIENT_BLOCK_GET_BY_NUM_REQUEST":            124,
	"CLIENT_PEERS_GET_REQUEST":                   125,
	"CLIENT_PEERS_GET_RESPONSE":                  126,
	"CLIENT_BLOCK_GET_BY_TRANSACTION_ID_REQUEST": 127,
	"CLIENT_BLOCK_GET_BY_BATCH_ID_REQUEST":       128,
	"CLIENT_STATUS_GET_REQUEST":                  129,
	"CLIENT_STATUS_GET_RESPONSE":                 130,
	"CLIENT_EVENTS_SUBSCRIBE_REQUEST":            500,
	"CLIENT_EVENTS_SUBSCRIBE_RESPONSE":           501,
	"CLIENT_EVENTS_UNSUBSCRIBE_REQUEST":          502,
	"CLIENT_EVENTS_UNSUBSCRIBE_RESPONSE":         503,
	"CLIENT_EVENTS":                              504,
	"CLIENT_EVENTS_GET_REQUEST":                  505,
	"CLIENT_EVENTS_GET_RESPONSE":                 506,
	"GOSSIP_MESSAGE":                             200,
	"GOSSIP_REGISTER":                            201,
	"GOSSIP_UNREGISTER":                          202,
	"GOSSIP_BLOCK_REQUEST":                       205,
	"GOSSIP_BLOCK_RESPONSE":                      206,
	"GOSSIP_BATCH_BY_BATCH_ID_REQUEST":           207,
	"GOSSIP_BATCH_BY_TRANSACTION_ID_REQUEST":     208,
	"GOSSIP_BATCH_RESPONSE":                      209,
	"GOSSIP_GET_PEERS_REQUEST":                   210,
	"GOSSIP_GET_PEERS_RESPONSE":                  211,
	"NETWORK_ACK":                                300,
	"NETWORK_CONNECT":                            301,
	"NETWORK_DISCONNECT":                         302,
	"AUTHORIZATION_CONNECTION_RESPONSE":          600,
	"AUTHORIZATION_VIOLATION":                    601,
	"AUTHORIZATION_TRUST_REQUEST":                602,
	"AUTHORIZATION_TRUST_RESPONSE":               603,
	"AUTHORIZATION_CHALLENGE_REQUEST":            604,
	"AUTHORIZATION_CHALLENGE_RESPONSE":           605,
	"AUTHORIZATION_CHALLENGE_SUBMIT":             606,
	"AUTHORIZATION_CHALLENGE_RESULT":             607,
	"PING_REQUEST":                               700,
	"PING_RESPONSE":                              701,
}

func (x Message_MessageType) String() string {
	return proto.EnumName(Message_MessageType_name, int32(x))
}
func (Message_MessageType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 0} }

// A list of messages to be transmitted together.
type MessageList struct {
	Messages []*Message `protobuf:"bytes,1,rep,name=messages" json:"messages,omitempty"`
}

func (m *MessageList) Reset()                    { *m = MessageList{} }
func (m *MessageList) String() string            { return proto.CompactTextString(m) }
func (*MessageList) ProtoMessage()               {}
func (*MessageList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *MessageList) GetMessages() []*Message {
	if m != nil {
		return m.Messages
	}
	return nil
}

// The message passed between the validator and client, containing the
// header fields and content.
type Message struct {
	// The type of message, used to determine how to 'route' the message
	// to the appropriate handler as well as how to deserialize the
	// content.
	MessageType Message_MessageType `protobuf:"varint,1,opt,name=message_type,json=messageType,enum=Message_MessageType" json:"message_type,omitempty"`
	// The identifier used to correlate response messages to their related
	// request messages.  correlation_id should be set to a random string
	// for messages which are not responses to previously sent messages.  For
	// response messages, correlation_id should be set to the same string as
	// contained in the request message.
	CorrelationId string `protobuf:"bytes,2,opt,name=correlation_id,json=correlationId" json:"correlation_id,omitempty"`
	// The content of the message, defined by message_type.  In many
	// cases, this data has been serialized with Protocol Buffers or
	// CBOR.
	Content []byte `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
}

func (m *Message) Reset()                    { *m = Message{} }
func (m *Message) String() string            { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()               {}
func (*Message) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Message) GetMessageType() Message_MessageType {
	if m != nil {
		return m.MessageType
	}
	return Message_DEFAULT
}

func (m *Message) GetCorrelationId() string {
	if m != nil {
		return m.CorrelationId
	}
	return ""
}

func (m *Message) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

func init() {
	proto.RegisterType((*MessageList)(nil), "MessageList")
	proto.RegisterType((*Message)(nil), "Message")
	proto.RegisterEnum("Message_MessageType", Message_MessageType_name, Message_MessageType_value)
}

func init() {
	proto.RegisterFile("github.com/rberg2/sawtooth-go-sdk/protobuf/validator_pb2/validator.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 1020 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x7c, 0x56, 0xdb, 0x72, 0xdb, 0x44,
	0x18, 0x46, 0x96, 0xd3, 0xa4, 0xeb, 0x24, 0x55, 0x37, 0x4e, 0xe3, 0x26, 0x69, 0x9a, 0x9a, 0x52,
	0x02, 0xcc, 0xb8, 0x33, 0xc9, 0x05, 0xd7, 0xb2, 0xbc, 0x38, 0x9a, 0x28, 0x92, 0x91, 0x56, 0x65,
	0xe8, 0x8d, 0xc6, 0xa9, 0xdd, 0xd6, 0x34, 0x89, 0x82, 0xad, 0xb6, 0x94, 0x33, 0x3c, 0x01, 0x57,
	0x3c, 0x05, 0xf0, 0x04, 0x70, 0x0f, 0xcc, 0x70, 0xbe, 0xe1, 0xcc, 0x4b, 0x70, 0xbe, 0xea, 0x4a,
	0xfe, 0x57, 0xda, 0xb5, 0xe4, 0x5c, 0xd9, 0xda, 0xef, 0xfb, 0xfe, 0xf3, 0x1e, 0xd0, 0xce, 0xa8,
	0xfb, 0x30, 0x0a, 0xc3, 0xe8, 0x6e, 0x30, 0xea, 0xdd, 0xbb, 0x7e, 0x32, 0x0c, 0xa3, 0xf0, 0xe0,
	0xfe, 0xed, 0xeb, 0x0f, 0xba, 0x87, 0x83, 0x5e, 0x37, 0x0a, 0x87, 0xc1, 0xc9, 0xc1, 0x76, 0xf6,
	0xd5, 0x48, 0x08, 0xf5, 0x1d, 0x54, 0xd9, 0xef, 0x8f, 0x46, 0xdd, 0x3b, 0x7d, 0x6b, 0x30, 0x8a,
	0xf0, 0x55, 0x34, 0x77, 0x34, 0xfe, 0x1c, 0xd5, 0x94, 0x4d, 0x75, 0xab, 0xb2, 0x3d, 0xd7, 0x00,
	0xdc, 0x4d, 0x91, 0xfa, 0x87, 0x55, 0x34, 0x0b, 0xab, 0xf8, 0x79, 0x34, 0x0f, 0xeb, 0x41, 0xf4,
	0xe8, 0xa4, 0xcf, 0x54, 0xca, 0xd6, 0xe2, 0x76, 0x95, 0xab, 0xf8, 0x2f, 0x65, 0x98, 0x5b, 0x39,
	0xca, 0x3e, 0xf0, 0x53, 0x68, 0xf1, 0x56, 0x38, 0x1c, 0xf6, 0x0f, 0xbb, 0xd1, 0x20, 0x3c, 0x0e,
	0x06, 0xbd, 0x5a, 0x89, 0x49, 0xcf, 0xba, 0x0b, 0xc2, 0xaa, 0xd9, 0xc3, 0x35, 0x34, 0x7b, 0x2b,
	0x3c, 0x8e, 0xfa, 0xc7, 0x51, 0x4d, 0x65, 0xf8, 0xbc, 0xcb, 0x3f, 0xeb, 0x1f, 0x2c, 0xa5, 0xb1,
	0x27, 0x06, 0x2b, 0x68, 0xb6, 0x45, 0x5e, 0xd0, 0x7d, 0x8b, 0x6a, 0x4f, 0xe0, 0x15, 0xb4, 0x44,
	0x3b, 0x81, 0x4b, 0xda, 0xa6, 0x47, 0x89, 0xcb, 0xfe, 0xbc, 0xe8, 0x13, 0x8f, 0x6a, 0x0a, 0xb3,
	0x57, 0x95, 0x01, 0xaf, 0xe3, 0xd8, 0x1e, 0xd1, 0x4a, 0xf8, 0x22, 0x5a, 0x66, 0x88, 0x6f, 0xe7,
	0x44, 0x2a, 0x5e, 0x45, 0x17, 0x26, 0x21, 0x90, 0x95, 0xf1, 0x05, 0x84, 0x19, 0xd6, 0x71, 0x1d,
	0x83, 0x78, 0x5e, 0xaa, 0x99, 0x81, 0x08, 0xb2, 0x75, 0x10, 0x9c, 0x81, 0x08, 0x3c, 0xaa, 0x53,
	0x12, 0xb4, 0x09, 0x4d, 0x25, 0xb3, 0x10, 0x81, 0x88, 0x80, 0x68, 0x4e, 0x12, 0x79, 0x82, 0xe8,
	0xac, 0x24, 0xf2, 0x44, 0x11, 0xc2, 0x6b, 0x68, 0x25, 0x85, 0x5a, 0xc4, 0x22, 0xec, 0x87, 0xeb,
	0x2a, 0x78, 0x1d, 0xd5, 0xf2, 0x20, 0x48, 0xe7, 0xf1, 0x65, 0xb4, 0x96, 0x94, 0xc9, 0x20, 0x66,
	0x87, 0x06, 0x7a, 0xab, 0x15, 0xb4, 0x74, 0xaa, 0xa7, 0xf2, 0x05, 0xbc, 0x89, 0xd6, 0x8b, 0x09,
	0x60, 0x62, 0x11, 0x42, 0x26, 0x37, 0x88, 0x3d, 0xc6, 0xb9, 0xf6, 0x1c, 0x84, 0x2c, 0x22, 0x20,
	0xd2, 0x62, 0xbf, 0x86, 0x65, 0xc6, 0x40, 0x53, 0xa7, 0xc6, 0x6e, 0xe0, 0xf9, 0xcd, 0x7d, 0x33,
	0x4b, 0xb7, 0x17, 0xfb, 0x2d, 0x26, 0x80, 0x89, 0x3e, 0xbe, 0x84, 0x2e, 0x72, 0x86, 0xe5, 0x18,
	0x7b, 0x81, 0xc5, 0x5a, 0x96, 0x1a, 0xb8, 0x8d, 0x37, 0xd0, 0x6a, 0x11, 0x0c, 0xf2, 0x3b, 0xb8,
	0x8e, 0x36, 0x24, 0x3c, 0x6e, 0x44, 0xf3, 0xe5, 0xc0, 0xcc, 0x12, 0xb8, 0x9b, 0x73, 0x21, 0x35,
	0x6b, 0x20, 0xc2, 0x49, 0x8c, 0x52, 0x04, 0xaf, 0x88, 0x11, 0x88, 0x30, 0xc8, 0xef, 0xc5, 0x9d,
	0x91, 0x70, 0x71, 0x48, 0x0e, 0x73, 0xc6, 0x25, 0xdf, 0x47, 0xf8, 0x49, 0x74, 0x19, 0x60, 0xea,
	0xea, 0xb6, 0xa7, 0x1b, 0xd4, 0x74, 0x6c, 0x39, 0x82, 0x63, 0xb6, 0xcd, 0x37, 0xa7, 0x93, 0xc0,
	0x54, 0x28, 0x54, 0x42, 0x64, 0x89, 0xd1, 0x9c, 0x4c, 0x71, 0x27, 0xc5, 0xf4, 0xaa, 0xd0, 0xb3,
	0xf1, 0xb8, 0x19, 0xbe, 0xeb, 0xc6, 0x5f, 0xdc, 0xcc, 0x10, 0x5f, 0x41, 0x97, 0xa6, 0x30, 0xc0,
	0xc8, 0x48, 0xc8, 0x7b, 0x4c, 0x91, 0x52, 0x8a, 0x84, 0xa2, 0x4a, 0x30, 0xc8, 0xef, 0x0b, 0x45,
	0xcd, 0xef, 0xbc, 0x07, 0x39, 0xe3, 0x52, 0x02, 0x0f, 0xf3, 0x53, 0xc9, 0x48, 0x7e, 0xb6, 0xd9,
	0x5f, 0xcb, 0x4f, 0x25, 0x27, 0x80, 0x89, 0x47, 0x42, 0x7c, 0x7c, 0xcf, 0x88, 0x11, 0xbc, 0x2e,
	0xb8, 0x90, 0x71, 0x30, 0xf0, 0x86, 0x50, 0x69, 0x69, 0x2e, 0x6d, 0x7f, 0x3f, 0xb5, 0xf2, 0xa6,
	0x90, 0x65, 0x87, 0x10, 0xd7, 0x93, 0x7c, 0xbc, 0x25, 0x64, 0x29, 0xa2, 0xe0, 0xe1, 0x6d, 0xdc,
	0x40, 0xcf, 0x16, 0x79, 0x10, 0x1b, 0x2b, 0xec, 0x82, 0x77, 0xf0, 0x33, 0xe8, 0x6a, 0x11, 0x7f,
	0x5c, 0x01, 0x81, 0xf9, 0xae, 0xc2, 0xb2, 0x17, 0xeb, 0xeb, 0xcb, 0x81, 0xbd, 0xa7, 0xb0, 0xec,
	0x57, 0x8b, 0x70, 0x08, 0xed, 0x7d, 0x85, 0x4d, 0x2c, 0xcf, 0x3e, 0x39, 0x36, 0xbc, 0x78, 0xdf,
	0x7b, 0x86, 0x6b, 0x36, 0xb3, 0x23, 0xed, 0x4f, 0x95, 0xdd, 0x29, 0x9b, 0xd3, 0x59, 0x60, 0xec,
	0x2f, 0x15, 0x5f, 0x43, 0x57, 0x64, 0x9a, 0x6f, 0xe7, 0xcd, 0xfd, 0xad, 0xe2, 0xa7, 0x51, 0xfd,
	0x34, 0x1e, 0x18, 0xfc, 0x47, 0xc5, 0x18, 0x2d, 0x48, 0x44, 0xed, 0x5f, 0x55, 0x48, 0x19, 0xc4,
	0x62, 0xca, 0xff, 0xa9, 0x42, 0xca, 0x12, 0x0e, 0x46, 0xff, 0x57, 0xf1, 0x12, 0x5a, 0x6c, 0x3b,
	0x9e, 0x67, 0x76, 0x82, 0x7d, 0x76, 0x83, 0xe8, 0x6d, 0xa2, 0x7d, 0xae, 0xe0, 0x2a, 0x3a, 0x07,
	0x8b, 0xfc, 0x2e, 0xd2, 0xbe, 0x50, 0xd8, 0x1d, 0x74, 0x1e, 0x56, 0xb3, 0x3b, 0x4a, 0xfb, 0x52,
	0x61, 0x07, 0x6d, 0x15, 0xd6, 0xc7, 0x1d, 0xe2, 0xee, 0xbf, 0x52, 0xd8, 0x95, 0xb6, 0x3c, 0x01,
	0x81, 0xe7, 0xaf, 0x95, 0xb8, 0x8c, 0x1c, 0x4b, 0x7a, 0x59, 0xd4, 0xd4, 0x6f, 0x14, 0xfc, 0x1c,
	0xba, 0x36, 0x49, 0x9b, 0x32, 0x2b, 0xdf, 0x4a, 0xfe, 0x12, 0x72, 0xea, 0xef, 0x3b, 0x85, 0xcd,
	0x65, 0x0d, 0xb0, 0xb8, 0x06, 0xe3, 0xd9, 0xe4, 0xd2, 0xef, 0x93, 0xe1, 0x29, 0x80, 0x41, 0xfe,
	0x83, 0x82, 0x35, 0x54, 0xb1, 0x09, 0x7d, 0xc9, 0x71, 0xf7, 0x02, 0xdd, 0xd8, 0xd3, 0x3e, 0x2a,
	0xc5, 0x55, 0xe2, 0x2b, 0x86, 0x63, 0xdb, 0xc4, 0xa0, 0xda, 0xc7, 0x25, 0x76, 0x23, 0x63, 0xbe,
	0xda, 0x32, 0x3d, 0x0e, 0x7c, 0x52, 0x8a, 0xe7, 0x41, 0xf7, 0xe9, 0xae, 0xe3, 0x9a, 0x37, 0xf5,
	0x24, 0x74, 0xc0, 0xe2, 0xbf, 0xa9, 0xa3, 0x1f, 0xcb, 0x6c, 0x77, 0xad, 0xc8, 0xbc, 0x1b, 0xa6,
	0x63, 0x25, 0xff, 0xb4, 0x9f, 0xca, 0xec, 0x0c, 0x58, 0x93, 0x51, 0xea, 0xfa, 0xc2, 0x11, 0xf5,
	0x73, 0x99, 0x9d, 0x72, 0xeb, 0xc5, 0x0c, 0x70, 0xf1, 0x4b, 0x39, 0x9e, 0xf3, 0x89, 0x50, 0x76,
	0x75, 0xcb, 0x22, 0x76, 0x3b, 0x1b, 0xcc, 0x5f, 0xcb, 0x71, 0x83, 0xa6, 0xb3, 0xc0, 0xd8, 0x6f,
	0x65, 0x76, 0x64, 0x6c, 0x4c, 0xa3, 0x8d, 0xaf, 0x4d, 0xed, 0xf7, 0x53, 0x49, 0xcc, 0x56, 0xfc,
	0x9a, 0xfa, 0xa3, 0x8c, 0xcf, 0xa3, 0xf9, 0x8e, 0x69, 0xb7, 0xd3, 0x18, 0x3e, 0x9d, 0x89, 0x67,
	0x1e, 0x96, 0xc0, 0xe1, 0x67, 0x33, 0xcd, 0x2d, 0xb4, 0xcc, 0x1f, 0xa1, 0x0d, 0xf6, 0x08, 0x6d,
	0xf0, 0x47, 0x68, 0x47, 0xb9, 0xb9, 0x20, 0xbd, 0x43, 0x0f, 0xce, 0x24, 0xd0, 0xce, 0xe3, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x55, 0x16, 0xa0, 0xf1, 0xb5, 0x0a, 0x00, 0x00,
}
